### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET http://localhost:8080/maintenance
Content-Type: */*

###

POST http://localhost:8080/maintenance/register
Content-Type: application/json

{
  "firstname": "Heiko",
  "lastname": "Vichtbauer",
  "email": "heiko.v3006@gmail.com",
  "password": "ja",
  "passwordConfirm": "ja"
}

###

POST http://localhost:8080/maintenance/login
Content-Type: application/json

{
  "email": "heiko.v3006@gmail.com",
  "password": "ja"
}

###

POST http://localhost:8080/maintenance/editProfile
Content-Type: application/json

{
  "email": "heiko.v3006@gmail.com",
  "password": "ja",
  "user": {
    "firstname": "Hugo",
    "lastname": "Vichtl",
    "email": "vichti@gmail.com",
    "password": "ja",
    "bikeList": null
  }
}

###

POST http://localhost:8080/maintenance/login
Content-Type: application/json

{
  "email": "vichti@gmail.com",
  "password": "ja"
}

###

POST http://localhost:8080/maintenance/delete
Content-Type: application/json

{
  "email": "heiko.v3006@gmail.com",
  "password": "ja"
}

###

POST http://localhost:8080/maintenance/addBike
Content-Type: application/json

{
  "fin": "JHASHDJJSHD",
  "email": "heiko.v3006@gmail.com",
  "bikeId": 1,
  "km": 30000,
  "imgUrl": "https://www.google.com"
}

###

POST http://localhost:8080/maintenance/deleteBikeFromUser
Content-Type: application/json

{
  "email": "heiko.v3006@gmail.com",
  "bikeId": 1,
  "fin": "JHASHDJJSHD"
}

###

POST http://localhost:8080/maintenance/addServiceHistory
Content-Type: application/json

{
  "email": "heiko.v3006@gmail.com",
  "fin": "JHASHDJJSHD",
  "serviceId": 1,
  "km": 9000
}

###

//Gesamte Historie eines Bikes für ein bestimmtes Service
GET http://localhost:8080/maintenance/getBikeserviceHistory
Content-Type: application/json

{
  "email": "heiko.v3006@gmail.com",
  "fin": "JHASHDJJSHD",
  "serviceId": 1
}

###

//letzter Serviceeintrag für ein spezifisches Bike und spezifisches Service
GET http://localhost:8080/maintenance/getBikeserviceHistory/last
Content-Type: application/json

{
  "email": "heiko.v3006@gmail.com",
  "fin": "JHASHDJJSHD",
  "serviceId": 1
}

###

GET http://localhost:8080/maintenance/getServicesByBike
Content-Type: application/json

{
  "bikeId": 2
}

###

GET http://localhost:8080/maintenance/getServiceListForSpecificBike
Content-Type: application/json

{
  "email": "heiko.v3006@gmail.com",
  "fin": "JHASHDJJSHD"
}