### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET http://localhost:8080/maintenance
Content-Type: */*

###

POST http://localhost:8080/maintenance/register
Content-Type: application/json

{
  "firstname": "Oliver",
  "lastname": "Schatzberger",
  "email": "heiko.v3006@gmail.com",
  "password": "ja",
  "passwordConfirm": "ja"
}

###

POST http://localhost:8080/maintenance/login
Content-Type: application/json

{
  "email": "oliver.schatzberger@outlook.com",
  "password": "ja"
}

###

POST http://localhost:8080/maintenance/editProfile
Content-Type: application/json

{
  "email": "heiko.v3006@gmail.com",
  "password": "ja",
  "user": {
    "firstname": "Hugo",
    "lastname": "Vichtl",
    "email": "vichti@gmail.com",
    "password": "ja",
    "bikeList": null
  }
}

###

POST http://localhost:8080/maintenance/login
Content-Type: application/json

{
  "email": "vichti@gmail.com",
  "password": "ja"
}

###

POST http://localhost:8080/maintenance/delete
Content-Type: application/json

{
  "email": "heiko.v3006@gmail.com",
  "password": "ja"
}

###

POST http://localhost:8080/maintenance/addBike
Content-Type: application/json

{
  "fin": "12325678901234562",
  "email": "heiko.v3006@gmail.com",
  "bikeId": 1,
  "km": 3000,
  "imgUrl": "https://www.google.com"
}

###

POST http://localhost:8080/maintenance/deleteBikeFromUser
Content-Type: application/json

{
  "email": "heiko.v3006@gmail.com",
  "bikeId": 1,
  "fin": "12345678901234567"
}

###

POST http://localhost:8080/maintenance/addServiceHistory
Content-Type: application/json

{
  "email": "heiko.v3006@gmail.com",
  "fin": "12325678901234562",
  "serviceId": 1,
  "km": 1000
}

###

POST http://localhost:8080/maintenance/addKmToBike
Content-Type: application/json

{
  "emailInput": "heiko.v3006@gmail.com",
  "finInput": "12345678901234567",
  "kmInput": 100
}

###

//Gesamte Historie eines Bikes für ein bestimmtes Service
GET http://localhost:8080/maintenance/getBikeserviceHistory/heiko.v3006@gmail.com/12345678901234567/1


###

//letzter Serviceeintrag für ein spezifisches Bike und spezifisches Service
GET http://localhost:8080/maintenance/getBikeserviceHistory/last/heiko.v3006@gmail.com/12345678901234567/1


###

GET http://localhost:8080/maintenance/getServicesByBike/1


###

GET http://localhost:8080/maintenance/getServiceListForSpecificBike/heiko.v3006@gmail.com/12345678901234567

###

GET http://localhost:8080/maintenance/getBikeserviceHistory/fin/12345678901234567