name: KTM Maintenance
run-name: Build Project 🚀
on:
  push:
    branches:
      - main

env:
  GITHUB_USER: ${{ github.repository_owner }}
  BACKEND_IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/backend:latest"

permissions:
  packages: write
  contents: read

jobs:
  backend:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: build backend
        run: |
          chmod +x ./build.sh
          ./build.sh
        working-directory: backend

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: push backend docker image
        run: |
          echo "tagging backend $BACKEND_IMAGE_NAME"
          docker tag backend $BACKEND_IMAGE_NAME
          docker push $BACKEND_IMAGE_NAME
  done:
    runs-on: ubuntu-24.04
    needs:
      - backend
    steps:
      - name: done
        run: |
          echo "# Demo Docker images pushed" >> $GITHUB_STEP_SUMMARY
          echo "## Steps to do" >> $GITHUB_STEP_SUMMARY
          echo "- do not forget to make **$BACKEND_IMAGE_NAME** and **$FRONTEND_IMAGE_NAME** public" >> $GITHUB_STEP_SUMMARY
          echo "- refresh the deployments in your cloud" >> $GITHUB_STEP_SUMMARY

